# Generated by Django 3.2.10 on 2023-02-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20230211_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdoc',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='name',
            field=models.CharField(default='No name', max_length=40, verbose_name='Имя документа'),
        ),
    ]
