# Generated by Django 3.2.10 on 2023-02-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0004_alter_clientdoc_options_clientdoc_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontainerrow',
            options={'ordering': ['client_name', 'date']},
        ),
        migrations.AddField(
            model_name='clientdoc',
            name='client_row_pos',
            field=models.CharField(choices=[('93:109', '93:109'), ('48:84', '48:84')], default='93:109', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='name',
            field=models.CharField(default='Без имени', max_length=40, verbose_name='Имя документа'),
        ),
    ]
