# Generated by Django 3.2.10 on 2023-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0005_auto_20230216_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdoc',
            name='document_file',
            field=models.FileField(blank=True, upload_to='containers/client_container'),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='client_row_pos',
            field=models.CharField(choices=[('93:109', '93:109'), ('48:75', '48:75')], default='93:109', max_length=10),
        ),
    ]
