# Generated by Django 3.2.18 on 2023-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0007_auto_20230312_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='')),
                ('is_read', models.BooleanField(default=False, editable=False)),
                ('text_file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='area_document',
            field=models.FileField(blank=True, upload_to='containers', verbose_name='Файл с номерами участков'),
        ),
        migrations.AlterField(
            model_name='clientdoc',
            name='document_file',
            field=models.FileField(upload_to='containers', verbose_name='Исходный документ'),
        ),
    ]
