# Generated by Django 3.2.18 on 2023-03-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0010_auto_20230313_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worddoc',
            name='rows_without_data',
        ),
    ]
