# Generated by Django 3.2.18 on 2023-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0011_remove_worddoc_rows_without_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddoc',
            name='rows_without_data',
            field=models.TextField(blank=True),
        ),
    ]
