# Generated by Django 3.2.18 on 2023-03-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0013_alter_worddoc_rows_without_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worddoc',
            old_name='text_file',
            new_name='result_text_file',
        ),
        migrations.RenameField(
            model_name='worddoc',
            old_name='doc_file',
            new_name='word_doc_file',
        ),
    ]
