# Generated by Django 3.2.18 on 2023-03-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0014_auto_20230314_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientDoc',
            new_name='ClientsReport',
        ),
        migrations.RenameField(
            model_name='worddoc',
            old_name='result_text_file',
            new_name='hand_text_file',
        ),
        migrations.RenameField(
            model_name='worddoc',
            old_name='is_read',
            new_name='is_doc_readable',
        ),
        migrations.AlterField(
            model_name='worddoc',
            name='rows_without_data',
            field=models.FileField(blank=True, editable=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='worddoc',
            name='word_doc_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
