# Generated by Django 3.2.18 on 2023-03-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0015_auto_20230315_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaDocFile',
        ),
        migrations.DeleteModel(
            name='ClientDocFile',
        ),
        migrations.AlterModelOptions(
            name='worddoc',
            options={'ordering': ['-pk']},
        ),
        migrations.CreateModel(
            name='AreaDocFile',
            fields=[
                ('worddoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='containers.worddoc')),
                ('type', models.CharField(default='Номера участков', max_length=30, verbose_name='Тип документа')),
            ],
            bases=('containers.worddoc',),
        ),
        migrations.CreateModel(
            name='ClientDocFile',
            fields=[
                ('worddoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='containers.worddoc')),
                ('type', models.CharField(choices=[('Книга выгрузки', 'Книга выгрузки'), ('Книга вывоза', 'Книга вывоза')], default='Книга выгрузки', max_length=30, verbose_name='Тип документа')),
            ],
            bases=('containers.worddoc',),
        ),
        migrations.AlterField(
            model_name='ClientsReport',
            name='client_container_doc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_container_doc', to='containers.clientdocfile'),
        ),
        migrations.AlterField(
            model_name='ClientsReport',
            name='area_doc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_doc', to='containers.areadocfile', verbose_name='Файл с номерами участков'),
        ),
    ]
