# Generated by Django 3.2.18 on 2023-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0016_auto_20230315_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsreport',
            name='client_row_pos',
        ),
        migrations.AddField(
            model_name='clientcontainerrow',
            name='nn',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcontainerrow',
            name='send_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcontainerrow',
            name='weight',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areadocfile',
            name='type',
            field=models.CharField(default='Номера участков', editable=False, max_length=30, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='worddoc',
            name='hand_text_file',
            field=models.FileField(blank=True, editable=False, upload_to=''),
        ),
    ]
