# Generated by Django 3.2.18 on 2023-04-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0018_auto_20230417_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='client_filter',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='client_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
