# Generated by Django 3.2.18 on 2023-04-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0020_auto_20230419_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceproxy',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containers.clientuser'),
        ),
    ]
