# Generated by Django 3.2.18 on 2023-04-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0021_faceproxy_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuser',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='faceproxy',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагент'},
        ),
        migrations.RemoveField(
            model_name='clientsreport',
            name='clients',
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='client_filter',
            field=models.CharField(max_length=30, unique=True, verbose_name='Искать по'),
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='client_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Полное имя'),
        ),
    ]
