services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./rw/media:/app/media
      - static_files:/app/static
    ports:
      - "127.0.0.1:8003:8000"

volumes:
  db_data:
  static_files:
