# Generated by Django 3.2.18 on 2025-02-18 13:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='books')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book_date', models.DateField(default=datetime.datetime(2025, 2, 18, 13, 10, 17, 832557, tzinfo=utc))),
                ('description', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('Книга вывоза по клиентам', 'Книга вывоза по клиентам'), ('Книга выгрузки', 'Книга выгрузки')], max_length=30)),
            ],
        ),
    ]
