# Generated by Django 3.2.18 on 2025-02-18 15:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='no_containers_file',
            field=models.FileField(blank=True, upload_to='books_no_containers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 18, 15, 28, 35, 435128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Книга вывоза по клиентам', 'Книга вывоза по клиентам'), ('Книга выгрузки', 'Книга выгрузки')], default='Книга вывоза по клиентам', max_length=30),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('client_name', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('nn', models.CharField(blank=True, max_length=5)),
                ('send_number', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=5)),
                ('area', models.PositiveIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.book')),
            ],
            options={
                'ordering': ['client_name', 'start_date'],
            },
        ),
    ]
