# Generated by Django 3.2.18 on 2025-02-18 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20250218_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='error_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 18, 18, 36, 43, 572839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='container',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', related_query_name='container', to='clients.book'),
        ),
    ]
