# Generated by Django 3.2.18 on 2025-02-19 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20250218_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='document',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 19, 11, 22, 17, 671236, tzinfo=utc)),
        ),
    ]
