# Generated by Django 3.2.18 on 2025-02-19 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20250219_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 19, 12, 3, 49, 362209, tzinfo=utc)),
        ),
    ]
