# Generated by Django 3.2.18 on 2025-03-19 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_book_book_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 19, 17, 55, 30, 489916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Книга вывоза по клиентам', 'Книга вывоза по клиентам'), ('Книга выгрузки', 'Книга выгрузки')], default='Книга выгрузки', max_length=30),
        ),
        migrations.AlterField(
            model_name='container',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
