# Generated by Django 3.2.18 on 2025-03-19 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20250319_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 17, 57, 54, 252668, tzinfo=utc)),
        ),
    ]
